[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"

[[prerender]]
  paths = ["/", "/work", "/about", "/blog", "/work/torres-heights", "/work/spaghetti", "/work/mrp", "/work/henley-spanish-centre"]
