[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build]
  publish = "build"  # Change this to "build" if you're using CRA or Vite
  command = "npm run build"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[context.production]
  command = "npm run build"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"


